apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-finder
  labels:
    app: movie-finder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-finder
  template:
    metadata:
      labels:
        app: movie-finder
    spec:
      containers:
      - name: movie-finder
        image: movie-finder:latest
        imagePullPolicy: Never # Use local image
        command:
        - -config
        - /app/config/agents.json
        - -proxy-docket
        - /app/config/proxy-docket.json
        - -workers
        - "16"
        - -timeout
        - "45s"
        env:
        - name: MOVIE_FINDER_PROXY
          value: ""
        - name: HTTP_PROXY
          value: ""
        - name: HTTPS_PROXY
          value: ""
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: movie-config
