// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proto/hotwire/v1/hotwire.proto

package hotwirev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BackendId       string                 `protobuf:"bytes,1,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
	P50Ms           float64                `protobuf:"fixed64,2,opt,name=p50_ms,json=p50Ms,proto3" json:"p50_ms,omitempty"`
	P99Ms           float64                `protobuf:"fixed64,3,opt,name=p99_ms,json=p99Ms,proto3" json:"p99_ms,omitempty"`
	ErrorRate       float64                `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	Inflight        int32                  `protobuf:"varint,5,opt,name=inflight,proto3" json:"inflight,omitempty"`
	Rps             float64                `protobuf:"fixed64,6,opt,name=rps,proto3" json:"rps,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,7,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricReport) Reset() {
	*x = MetricReport{}
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricReport) ProtoMessage() {}

func (x *MetricReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricReport.ProtoReflect.Descriptor instead.
func (*MetricReport) Descriptor() ([]byte, []int) {
	return file_proto_hotwire_v1_hotwire_proto_rawDescGZIP(), []int{0}
}

func (x *MetricReport) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

func (x *MetricReport) GetP50Ms() float64 {
	if x != nil {
		return x.P50Ms
	}
	return 0
}

func (x *MetricReport) GetP99Ms() float64 {
	if x != nil {
		return x.P99Ms
	}
	return 0
}

func (x *MetricReport) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *MetricReport) GetInflight() int32 {
	if x != nil {
		return x.Inflight
	}
	return 0
}

func (x *MetricReport) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *MetricReport) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type WeightAssignment struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BackendId       string                 `protobuf:"bytes,1,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
	Weight          float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,3,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WeightAssignment) Reset() {
	*x = WeightAssignment{}
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightAssignment) ProtoMessage() {}

func (x *WeightAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightAssignment.ProtoReflect.Descriptor instead.
func (*WeightAssignment) Descriptor() ([]byte, []int) {
	return file_proto_hotwire_v1_hotwire_proto_rawDescGZIP(), []int{1}
}

func (x *WeightAssignment) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

func (x *WeightAssignment) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *WeightAssignment) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotwire_v1_hotwire_proto_rawDescGZIP(), []int{2}
}

type WeightUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Weights         []*BackendWeight       `protobuf:"bytes,1,rep,name=weights,proto3" json:"weights,omitempty"`
	Reason          string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,3,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WeightUpdate) Reset() {
	*x = WeightUpdate{}
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightUpdate) ProtoMessage() {}

func (x *WeightUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightUpdate.ProtoReflect.Descriptor instead.
func (*WeightUpdate) Descriptor() ([]byte, []int) {
	return file_proto_hotwire_v1_hotwire_proto_rawDescGZIP(), []int{3}
}

func (x *WeightUpdate) GetWeights() []*BackendWeight {
	if x != nil {
		return x.Weights
	}
	return nil
}

func (x *WeightUpdate) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *WeightUpdate) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type BackendWeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BackendId     string                 `protobuf:"bytes,1,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
	Weight        float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	P99Ms         float64                `protobuf:"fixed64,4,opt,name=p99_ms,json=p99Ms,proto3" json:"p99_ms,omitempty"`
	ErrorRate     float64                `protobuf:"fixed64,5,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendWeight) Reset() {
	*x = BackendWeight{}
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendWeight) ProtoMessage() {}

func (x *BackendWeight) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendWeight.ProtoReflect.Descriptor instead.
func (*BackendWeight) Descriptor() ([]byte, []int) {
	return file_proto_hotwire_v1_hotwire_proto_rawDescGZIP(), []int{4}
}

func (x *BackendWeight) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

func (x *BackendWeight) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BackendWeight) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BackendWeight) GetP99Ms() float64 {
	if x != nil {
		return x.P99Ms
	}
	return 0
}

func (x *BackendWeight) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

type ListBackendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsRequest) Reset() {
	*x = ListBackendsRequest{}
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsRequest) ProtoMessage() {}

func (x *ListBackendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsRequest.ProtoReflect.Descriptor instead.
func (*ListBackendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hotwire_v1_hotwire_proto_rawDescGZIP(), []int{5}
}

type ListBackendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backends      []*BackendState        `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsResponse) Reset() {
	*x = ListBackendsResponse{}
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsResponse) ProtoMessage() {}

func (x *ListBackendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsResponse.ProtoReflect.Descriptor instead.
func (*ListBackendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hotwire_v1_hotwire_proto_rawDescGZIP(), []int{6}
}

func (x *ListBackendsResponse) GetBackends() []*BackendState {
	if x != nil {
		return x.Backends
	}
	return nil
}

type BackendState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BackendId        string                 `protobuf:"bytes,1,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
	Weight           float64                `protobuf:"fixed64,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Score            float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	P99Ms            float64                `protobuf:"fixed64,4,opt,name=p99_ms,json=p99Ms,proto3" json:"p99_ms,omitempty"`
	P50Ms            float64                `protobuf:"fixed64,5,opt,name=p50_ms,json=p50Ms,proto3" json:"p50_ms,omitempty"`
	ErrorRate        float64                `protobuf:"fixed64,6,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	Inflight         int32                  `protobuf:"varint,7,opt,name=inflight,proto3" json:"inflight,omitempty"`
	Rps              float64                `protobuf:"fixed64,8,opt,name=rps,proto3" json:"rps,omitempty"`
	LastReportUnixMs int64                  `protobuf:"varint,9,opt,name=last_report_unix_ms,json=lastReportUnixMs,proto3" json:"last_report_unix_ms,omitempty"`
	Stale            bool                   `protobuf:"varint,10,opt,name=stale,proto3" json:"stale,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BackendState) Reset() {
	*x = BackendState{}
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendState) ProtoMessage() {}

func (x *BackendState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hotwire_v1_hotwire_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendState.ProtoReflect.Descriptor instead.
func (*BackendState) Descriptor() ([]byte, []int) {
	return file_proto_hotwire_v1_hotwire_proto_rawDescGZIP(), []int{7}
}

func (x *BackendState) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

func (x *BackendState) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BackendState) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *BackendState) GetP99Ms() float64 {
	if x != nil {
		return x.P99Ms
	}
	return 0
}

func (x *BackendState) GetP50Ms() float64 {
	if x != nil {
		return x.P50Ms
	}
	return 0
}

func (x *BackendState) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *BackendState) GetInflight() int32 {
	if x != nil {
		return x.Inflight
	}
	return 0
}

func (x *BackendState) GetRps() float64 {
	if x != nil {
		return x.Rps
	}
	return 0
}

func (x *BackendState) GetLastReportUnixMs() int64 {
	if x != nil {
		return x.LastReportUnixMs
	}
	return 0
}

func (x *BackendState) GetStale() bool {
	if x != nil {
		return x.Stale
	}
	return false
}

var File_proto_hotwire_v1_hotwire_proto protoreflect.FileDescriptor

const file_proto_hotwire_v1_hotwire_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/hotwire/v1/hotwire.proto\x12\n" +
	"hotwire.v1\"\xd4\x01\n" +
	"\fMetricReport\x12\x1d\n" +
	"\n" +
	"backend_id\x18\x01 \x01(\tR\tbackendId\x12\x15\n" +
	"\x06p50_ms\x18\x02 \x01(\x01R\x05p50Ms\x12\x15\n" +
	"\x06p99_ms\x18\x03 \x01(\x01R\x05p99Ms\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\x12\x1a\n" +
	"\binflight\x18\x05 \x01(\x05R\binflight\x12\x10\n" +
	"\x03rps\x18\x06 \x01(\x01R\x03rps\x12*\n" +
	"\x11timestamp_unix_ms\x18\a \x01(\x03R\x0ftimestampUnixMs\"u\n" +
	"\x10WeightAssignment\x12\x1d\n" +
	"\n" +
	"backend_id\x18\x01 \x01(\tR\tbackendId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\x12*\n" +
	"\x11timestamp_unix_ms\x18\x03 \x01(\x03R\x0ftimestampUnixMs\"\x12\n" +
	"\x10SubscribeRequest\"\x87\x01\n" +
	"\fWeightUpdate\x123\n" +
	"\aweights\x18\x01 \x03(\v2\x19.hotwire.v1.BackendWeightR\aweights\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12*\n" +
	"\x11timestamp_unix_ms\x18\x03 \x01(\x03R\x0ftimestampUnixMs\"\x92\x01\n" +
	"\rBackendWeight\x12\x1d\n" +
	"\n" +
	"backend_id\x18\x01 \x01(\tR\tbackendId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x15\n" +
	"\x06p99_ms\x18\x04 \x01(\x01R\x05p99Ms\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x05 \x01(\x01R\terrorRate\"\x15\n" +
	"\x13ListBackendsRequest\"L\n" +
	"\x14ListBackendsResponse\x124\n" +
	"\bbackends\x18\x01 \x03(\v2\x18.hotwire.v1.BackendStateR\bbackends\"\x9b\x02\n" +
	"\fBackendState\x12\x1d\n" +
	"\n" +
	"backend_id\x18\x01 \x01(\tR\tbackendId\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x01R\x06weight\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x15\n" +
	"\x06p99_ms\x18\x04 \x01(\x01R\x05p99Ms\x12\x15\n" +
	"\x06p50_ms\x18\x05 \x01(\x01R\x05p50Ms\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x06 \x01(\x01R\terrorRate\x12\x1a\n" +
	"\binflight\x18\a \x01(\x05R\binflight\x12\x10\n" +
	"\x03rps\x18\b \x01(\x01R\x03rps\x12-\n" +
	"\x13last_report_unix_ms\x18\t \x01(\x03R\x10lastReportUnixMs\x12\x14\n" +
	"\x05stale\x18\n" +
	" \x01(\bR\x05stale2\xfc\x01\n" +
	"\fControlPlane\x12K\n" +
	"\rReportMetrics\x12\x18.hotwire.v1.MetricReport\x1a\x1c.hotwire.v1.WeightAssignment(\x010\x01\x12L\n" +
	"\x10SubscribeWeights\x12\x1c.hotwire.v1.SubscribeRequest\x1a\x18.hotwire.v1.WeightUpdate0\x01\x12Q\n" +
	"\fListBackends\x12\x1f.hotwire.v1.ListBackendsRequest\x1a .hotwire.v1.ListBackendsResponseB\"Z hotwire/gen/hotwire/v1;hotwirev1b\x06proto3"

var (
	file_proto_hotwire_v1_hotwire_proto_rawDescOnce sync.Once
	file_proto_hotwire_v1_hotwire_proto_rawDescData []byte
)

func file_proto_hotwire_v1_hotwire_proto_rawDescGZIP() []byte {
	file_proto_hotwire_v1_hotwire_proto_rawDescOnce.Do(func() {
		file_proto_hotwire_v1_hotwire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hotwire_v1_hotwire_proto_rawDesc), len(file_proto_hotwire_v1_hotwire_proto_rawDesc)))
	})
	return file_proto_hotwire_v1_hotwire_proto_rawDescData
}

var file_proto_hotwire_v1_hotwire_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_hotwire_v1_hotwire_proto_goTypes = []any{
	(*MetricReport)(nil),         // 0: hotwire.v1.MetricReport
	(*WeightAssignment)(nil),     // 1: hotwire.v1.WeightAssignment
	(*SubscribeRequest)(nil),     // 2: hotwire.v1.SubscribeRequest
	(*WeightUpdate)(nil),         // 3: hotwire.v1.WeightUpdate
	(*BackendWeight)(nil),        // 4: hotwire.v1.BackendWeight
	(*ListBackendsRequest)(nil),  // 5: hotwire.v1.ListBackendsRequest
	(*ListBackendsResponse)(nil), // 6: hotwire.v1.ListBackendsResponse
	(*BackendState)(nil),         // 7: hotwire.v1.BackendState
}
var file_proto_hotwire_v1_hotwire_proto_depIdxs = []int32{
	4, // 0: hotwire.v1.WeightUpdate.weights:type_name -> hotwire.v1.BackendWeight
	7, // 1: hotwire.v1.ListBackendsResponse.backends:type_name -> hotwire.v1.BackendState
	0, // 2: hotwire.v1.ControlPlane.ReportMetrics:input_type -> hotwire.v1.MetricReport
	2, // 3: hotwire.v1.ControlPlane.SubscribeWeights:input_type -> hotwire.v1.SubscribeRequest
	5, // 4: hotwire.v1.ControlPlane.ListBackends:input_type -> hotwire.v1.ListBackendsRequest
	1, // 5: hotwire.v1.ControlPlane.ReportMetrics:output_type -> hotwire.v1.WeightAssignment
	3, // 6: hotwire.v1.ControlPlane.SubscribeWeights:output_type -> hotwire.v1.WeightUpdate
	6, // 7: hotwire.v1.ControlPlane.ListBackends:output_type -> hotwire.v1.ListBackendsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_hotwire_v1_hotwire_proto_init() }
func file_proto_hotwire_v1_hotwire_proto_init() {
	if File_proto_hotwire_v1_hotwire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hotwire_v1_hotwire_proto_rawDesc), len(file_proto_hotwire_v1_hotwire_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hotwire_v1_hotwire_proto_goTypes,
		DependencyIndexes: file_proto_hotwire_v1_hotwire_proto_depIdxs,
		MessageInfos:      file_proto_hotwire_v1_hotwire_proto_msgTypes,
	}.Build()
	File_proto_hotwire_v1_hotwire_proto = out.File
	file_proto_hotwire_v1_hotwire_proto_goTypes = nil
	file_proto_hotwire_v1_hotwire_proto_depIdxs = nil
}
